unit/source_unit.go

`sourcegraph/srclib-javascript` expects that unit json will always contain `Files` key.
Fixes sourcegraph/srclib-javascript#11.
This should have no side effects in other toolchains, but I didn't check.

unit: don't omit empty `Files` slice when marshaling.

---

src/remote_import_build_data_cmd.go

Returns error if a build fails to import, instead of just logging it.

Return error on import failure

---

toolchain/find.go
toolchain/find_test.go

Seems like I manage to use srclib in unorthodox ways.
Basically I figured why not set $SRCLIBPATH to something like `$HOME/.srclib:$GOPATH/src` (it as it turns out not a good idea anyway).
And one of the packages had a symlink to file which broke `toolchain.List`
Before fix it would fail with:
> lstat /some/something/README.md: not a directory
if `README.md` was a symlink.

toolchain: fix find failing when directory contains file symlink

---

src/toolchain_cmd.go
toolchain/temp_dir.go

Should still decide on temp dir location. Using `~/.srclib/tmp` doesn't seem to be wise since `src` also looks for toolchains there.

Add temp dir cmd

---

docs/sources/plugins/atom.md
docs/theme/home.html

Dear  friends,
The homepage will have the same first alinea  as docs/overview.md and it will contain our Twitter names. Furthermore the Sourcegraph-Atom doc has 2 install methods now.
Best regards,
Jelmer de Reus

Updating homepage and Sourcegraph-Atom installation

---

README.md
docs/sources/overview.md
docs/theme/community.html
docs/theme/home.html

Extend the documentation overview  page. Add slack to the homepage and docs and community page.
README.md
docs/sources/overview.md
docs/theme/home.html
docs/theme/community.html

Docsoverview

---

src/push_cmd.go

`src push` is a wrapper around `src build-data upload` and `src remote
import-build` both of which support the `--commit` flag. This commit implements
optionally specifying commit for `src push`, so one does not need to checkout
the wanted revision.

Implement src push --commit

---

config/external.go
config/validate.go
config/validate_test.go
env.go
flagutil/marshal.go
graph/repo.go
plan/data.go
plan/makefile.go
plan/makefile_test.go
src/api_cmds.go
src/build_data_cmds.go
src/cli.go
src/doall_cmd_test.go
src/lint_cmd.go
src/misc.go
src/query_cmd.go
src/toolchain_cmd.go
src/units_cmd.go
toolchain/add.go
toolchain/find.go
toolchain/find_test.go
toolchain/get.go
toolchain/temp_dir.go
toolchain/toolchain.go

First round of Windows fixes. So far this is mostly simple fixes like dealing with path separators and path list separators properly.
There's some iffy stuff in the toolchain command code (which I also couldn't get working just yet due to symlink issues), but most of the rest of it should be pretty safe. I'll call that out in the comments on those lines.
The tests all pass locally for me on *nix, but that doesn't mean it's all happily working. Warrants some close scrutiny just due to how many things this touches.
Part of #149

Windows fixes

---

cmd/src/src.go

Writes `os.Args` and `err.Error()` to `stderr`. This way you can also see
failures in the subprocesses that src manages.
An example of failure output is
```
$ src make
fork/exec /Users/keegan/.srclib/sourcegraph.com/sourcegraph/srclib-python/.env/bin/virtualenv: no such file or directory
exit status 1
EOF
FAILED: src internal normalize-graph-data --unit-type PythonProgram --dir . - EOF
.srclib-cache/16a4943ad6c9d7cc333e64c7d1d366b2c461144e/PythonProgram.graph.json: command failed: src tool --methods program,docker "sourcegraph.com/sourcegraph/srclib-python" "graph" < .srclib-cache/16a4943ad6c9d7cc333e64c7d1d366b2c461144e/PythonProgram.unit.json | src internal normalize-graph-data --unit-type "PythonProgram" --dir . 1> .srclib-cache/16a4943ad6c9d7cc333e64c7d1d366b2c461144e/PythonProgram.gra …
```

cmd/src: Make it clearer that an error occurred

---

dep/rule.go
grapher/rule.go
plan/makefile.go
src/make_cmd.go
src/makefile_cmd.go

* --verbose flag for make and makefile subcommands
* Extra logging around target creation in verbose mode
* Final output line with colourized info indicating build success or failure

Make `src make` more informative

---

graph/repo.go
graph/repo_test.go

If a user clones a local repo with `git clone /path/to/repo /path/to/destrepo` the remote URL is a path `/path/to/destrepo`. We didn't error out from `TryMakeURI` on these inputs.

graph: Handle file paths passed to `TryMakeURI`

---

toolchain/find.go

Fixes #157. Shouldn't contain breaking changes.
Personally I'd define `ErrToolchainNotFound` and use that, but as sqs mentioned using `&os.PathError` is backwards compatible.
I checked across sourgraph projects and none is using error string matching instead of `os.IsNotFound` so everything looks good.

toolchain: use more descriptive error in `Lookup`.

---

cli/toolchain_cmd.go
env.go
toolchain/add.go
toolchain/bundle.go
toolchain/bundle_test.go
toolchain/config.go
toolchain/find.go
toolchain/get.go
toolchain/temp_dir.go
toolchain/toolchain.go

Toolchain bundles are .tar.gz archives of precompiled srclib toolchains.
Binary distribution of toolchains allows people to install and use toolchains
without needing to compile them (which often requires many
difficult-to-install dependencies).
Toolchains define how their bundles are created and what bundle variants (for
cross-compilation) should be built. Then users can install the bundles by
downloading the .tar.gz archive and running
'srclib toolchain unbundle <FILE>'.
**Dependent PRs**
* https://github.com/sourcegraph/srclib-go/pull/40
* https://github.com/sourcegraph/srclib-java/pull/30

toolchain: add support for prebuilt toolchain bundles

---

ann/ann.pb.go
ann/ann.proto
ann/gen.go
graph/def.pb.go
graph/def.proto
graph/gen.go
store/pb/gen.go
unit/gen.go

Add support for running go generate successfully on OS X.
Add support for running go generate with multiple GOPATH workspaces.
Use `(gogoproto.customtype) = "encoding/json.RawMessage"` instead of doing it via custom sed string substitution.

Make go generate directives work on more setups.

---

ann/ann.pb.go
ann/ann.proto
ann/gen.go
graph/def.pb.go
graph/def.proto
graph/gen.go
store/pb/gen.go
unit/gen.go

Use (gogoproto.customtype) = "sourcegraph.com/sqs/pbtypes.RawMessage" instead of "encoding/json.RawTypes", since the latter does not implement `proto.{Marshal,Unmarshal}`.
This restores change done in #177 (temporarily reverted due to the issue that this PR fixes). /cc @beyang
Depends on sqs/pbtypes#1 being merged.

Fix json.RawMessage issue with proto.{Marshal,Unmarshal}.

---

store/unit_store.go

If one of our filters is a `limiter`, then we can avoid querying additional
unit stores if our limit is reached. On a large synthetic repo (500 units) this
took query time from 15s to 6s. This was an FS backed store through sourcegraph
on my MBA. The limit used is 2. Most of the 6s time is dominated by
unmarshalling the index, rather than the queries.

perf: Query limit filter in unitstore.Refs

---

.gitignore
store/def_files_index.go
store/def_query_index.go
store/def_query_tree_index.go
store/def_ref_units_index.go
store/def_refs_index.go
store/fs_store.go
store/index_cache.go
store/index_cache_test.go
store/indexed.go
store/indexed_test.go

IndexedTreeStore contains a few indexes used by most queries. In some repos these can be large and the time to read, gunzip and unmarshal can be costly. This commit adds a simple in-memory cache around the indexes. The places where we `get` and `put` from the cache are only done where the index is read only, so we do not have to concern ourselves with making the Indexes handle concurrent writes.
In a synthetic repo on my MBA some queries took 6s, most of that time was dominated by loading indexes in `IndexedTreeStore`. In particular I generated a repo with
```bash
$ srclib gen-data urefs -v -u 500 -f 10 -r 'tmp/genrepo11' --ndefs 10 --gen-source
```
then did the `ListExamples` operation in sourcegraph.

store: In memory cache for IndexedTreeStore

---

.travis.yml
Makefile
cli/toolchain_cmd.go
docs/sources/install.md
docs/theme/home.html
integration/Dockerfile

Instead, error out right away when they fail. If someone runs `srclib toolchain install-std`
then they expect every toolchain to be installed, not for some to be skipped
(the user may potentially miss the error among all the log output). Likewise if
the user wants to explicitly install a given toolchain (e.g. `srclib toolchain install go`)
they do not want it to skip installation due to an error.
For example, trying to install the Go toolchain without $GOPATH set now produces:
```
$ srclib toolchain install go
Go (sourcegraph.com/sourcegraph/srclib-go) ====================================
failed to install/upgrade Go (sourcegraph.com/sourcegraph/srclib-go) toolchain:
Refusing to install Go toolchain because there is no GOPATH environment variable
set.
Note: Please ensure that Go 1.4+ is …
```

cli: do not skip installation of toolchains

---

store/def_query_tree_index.go

There are situations where `x.mt.t` is nil, so doing `node, i := x.mt.t.IndexedTraverse([]rune(q))` results in a nil pointer dereference panic.
This is a quick fix to prevent a panic. A proper fix will be to avoid calling `getByQuery` when the mafsaTable is not built/read.

store.defQueryTreeIndex: Prevent possible nil pointer dereference panic.

---

cli/config_cmd.go

The the file closing was deferred and then also closed
immediately. Changed to simply defer the close and log
it on failure.
Also removed an execution of chmod -R 777 on the repository
being configured. This isn't needed, when a volume is mounted,
the srclib user should be able to write to files without doing
this. Confirmed manually with the same src-preconfigcommands
Docker image. The user could nuke the entire filesystem if so
desired.

cli: Fix double file close and remove unnecessary chmod.

---

Godeps/Godeps.json
ann/ann.pb.go
graph/def.pb.go
graph/doc.pb.go
graph/output.pb.go
graph/ref.pb.go
store/pb/srcstore.pb.go
unit/unit.pb.go

Updated github.com/gogo/protobuf to commit `200875` and did `go generate ./...`

proto: re-generate protobufs with latest gogo/protobuf

---

cli/config_cmd.go

This change reverts a part of PR #212 / 3dcee737b542f81af862a93449eb9deb855cce3f which
removed a hack on the pretense that it worked fine locally without it. Although it is
true that it works fine without it locally (e.g. running `srclib config -m docker` works),
we are seeing failures to build the github.com/golang/go repository due to file permission
errors:
```
PreConfigCommands: command "\nif [ -d /home/srclib ]; then\ncurl -L 'https://storage.googleapis.com/golang/go1.4.1.linux-amd64.tar.gz' > /tmp/go1.4.tgz &&\nmkdir /home/srclib/go1.4 &&\ntar -xf /tmp/go1.4.tgz -C /home/srclib/go1.4 --strip-components=1\nfi &&\ncd src\n./make.bash\n": exit status 2
```
Suspected is that older Docker versions handle the file permissions differently, thus it works
locally but not in prod.

cli: revert a part of PR #212

---

Godeps/Godeps.json
dep/rule.go
flagutil/marshal.go
flagutil/marshal_test.go
grapher/grapher.go
grapher/rule.go
util/makefile.go
util/makefile_other.go
util/makefile_windows.go

- When running srclib in sgx environment, command name on Windows looks like "C:/foo/src.exe srclib". Cygwin environment does not handle propely case when command name contains un-escaped colon. In order to fix this issue, escaping first colon in command name on Windows and changing backslashes to slashes to make both `make` and `sh` happy
- Updated sourcegraph.com/sourcegraph/go-flags to sourcegraph/go-flags@7c86b1bed79b1dd42ee6650b6789776c40f78e12
- Java toolchain produces char-based offsets, we should convert them into byte-based offsets assuming that source code encoding is UTF-8. No CJK support yet

Fixed behavior in sgx mode; updated go-flags; converting char offsets to byte ones

---

Godeps/Godeps.json
toolchain/docker.go

As of recent versions of Docker (e.g. boot2docker 1.3.0 and Docker Toolbox) only
TLS connections to the Docker daemon are allowed. This adds support for TLS so
that everything works out-of-the-box. Please see the code comments for additional
info.

toolchain: add support for Docker TLS (required for newer versions of Docker)

---

cli/test_cmd.go
dep/resolve.go
graph/repo.go
grapher/grapher.go
toolchain/toolchain.go

- removed hack for srclib-java in Docker mode
- returning error instead of panicking when we were unable to normalize repo clone URI

Improvements for docker mode

---

grapher/rule.go
plan/makefile_test.go

- When file is present in unit's Files section but it's absent on disk, we should exclude it from Makefile prerequisites instead of terminating program execution. This situation may occur for example when file is being generated during compile phase if toolchain runs in the Docker mode: generated source file may be detected and included into Files, but after Docker container is stopped, file is no longer accessible.

Tolerating missing files

---

toolchain/toolchain.go

What we run is ephemeral, but docker by default leaves the container around even
once it has exited. This is causing issues in production since we have 10s of
thousands instances in `docker ps -a`, which seems to be causing perf issues in
docker.

docker: Use --rm for run

---

buildstore/store.go
cli/repo_config.go
cli/store_cmds.go
config/cached.go
gendata/simple.go
gendata/urefs.go
scan/scan.go
store/fs_store.go
store/indexed.go
store/indexes.go
store/repo_store.go
store/unit_store.go

`code.google.com/p/rog-go -> github.com/rogpeppe/rog-go`
This is to eliminate the need for `hg` when building srclib. This is the last `hg` dep.

update import path for rog-go

---

dep/rule.go
grapher/rule.go
toolchain/choose.go
toolchain/find.go

Removes the SRCLIB_NO_TOOLCHAINS env var, which permitted `srclib
store import` operations (and other things that depended on already
produced data) even when no toolchains were present. This behavior is
now the standard behavior.
This could make it slightly more confusing if you are trying to debug
why a scanned source unit is not being passed to a grapher (e.g., if
you specify the wrong ToolRef to use to graph the source unit), but it
comes at a significant decrease in complexity overall.

allow importing when no toolchains are present

---

cli/api_cmds.go
cli/cli.go
cli/config_cmd.go
cli/doall_cmd.go
cli/gen_data_cmd.go
cli/info_cmds.go
cli/internal_data_cmds.go
cli/lint_cmd.go
cli/make_cmd.go
cli/makefile_cmd.go
cli/repo_cmds.go
cli/selfupdate_cmd.go
cli/store_cmds.go
cli/test_cmd.go
cli/tool_cmd.go
cli/toolchain_cmd.go
cli/units_cmd.go
cli/version_cmd.go

This lets you create another program "myprogram" that mounts srclib's CLI as "myprogram srclib ...". For example, "myprogram srclib toolchain list" would run that subcommand of srclib.
Mostly an internal change only likely to affect (and benefit) Sourcegraph.

cli: expose AddCommands to allow mounting srclib as a subcommand of another CLI

---

cli/store_cmds.go
store/bench_test.go
store/filter.go
store/repo_store_test.go
store/tree_store_test.go
store/unit_store_test.go

This change adds a `exact` flag to the `ByFiles` filter such that it will
not be inclusive of files matching the prefix (e.g. `foo/` does not match
`foo/bar.go`).

{store,cli}: add specific option (no prefixes) to ByFiles

---

grapher/grapher.go

When source code contains multibyte UTF-8 characters there is a lot of "Changed pos X to Y in foo/bar" messages in log. I think they are useless and pollute logs so I propose to remove them

Removed garbage log output

---

Godeps/Godeps.json
grapher/grapher.go

- Bumping version of `github.com/sqs/fileset` to include recent changes related to UTF-8 BOM support
- `srclib-csharp` emits defs and refs character-based offsets so they need to be converted to byte ones.

Handling UTF-8 BOM and adjusting srclib-csharp offsets

---

config/validate.go
unit/source_unit.go

- using Unix-style separator for Srcfile's Files
- converting Files to Unix style during validation

Windows support: dealing with Srcfile

---

graph/repo.go
graph/repo_test.go

- adding SCM URL handling, now we should support the following URLs:
- protocol:... (https://foo.bar)
- vcs:... (git://foo.bar)
- vcs:protocol:.... (git:https://foo.bar)
- scm:vcs:protocol:... (scm:hg:https://foo.bar)
- host:path (assumed SSH)

Fixes sourcegraph/srclib#242

---

cli/store_cmds.go

Sometimes, `buildDataFS` is a virtual FS (e.g., zipfs), in which case `os.IsNotExist(err) == false`.
This fixes an issue that causes the import step to fail completely in Sourcegraph if any file is not found (which happens frequently on larger repositories, where srclib might fail on some source units).

robust file-not-found check

---

cli/api_cmds.go

- converting --file argument of `srclib api describe` and `srclib api list` to Unix-style

Windows support for 'srclib api'

---

cli/validate_cmd.go

validate_cmd: not checking this error is causing a nil dereference.

---

cli/toolchain_cmd.go

TypeScript toolchain installation does not work (all others as well), I've tested solution and it works using address 'sourcegraph.com/github.com/sourcegraph/srclib-typescript' instead of 'sourcegraph.com/sourcegraph/srclib-typescript'. Committed without 'github.com' extract, someone needs to fix it for all toolchains.

Add typescript toolchain support

---

cli/coverage_cmd.go
cli/store_cmds.go
cli/util.go

This is related to srclib import failing with io.EOF errors while
reading a JSON file. An io.EOF file is thrown by the JSON decoder if it
is passed a io.Reader that immediately sends an io.EOF ( i.e. an empty
file ).
@beyang

cli: properly handle reading an empty json file

---

cli/toolchain_cmd.go

The sourcegraph.com urls 404. Once that's fixed, everything seems fine.

Fix urls of toolchains: s/sourcegraph.com/github.com/

---

contrib/completion/_srclib
contrib/completion/srclib-completion.bash
docs/sources/install.md

.srclib-cache is fine, but we really need .srclib-store, which can be generated
using:
$ srclib store import
Then, let's prompt the user to execute her first command that actually does
something with the data:
$ srclib store defs
Also, add zsh completion.

docs/install: elaborate on usage (store subcommands) + add zsh completion

---

cli/coverage_cmd.go
cli/coverage_test.go

- when computing density, excluding blank and commented out lines (assuming that comment starts with //)
- when processing repository with multiple units, collecting all definitions before looking for them in the references. Otherwise we may found no definition if it was defined in a different unit
- using {unit, unit type, path} when matching refs to defs; normalizing ref.DefKey and def.DefKey objects before matching them. This is done to prevent cache misses when ref points to definition from the other unit (def has no unit/unittype set while ref includes not-empty defunit/defunitype)
- Windows support (using slashes as separators)

`srclib coverage` improvements

---

cli/coverage_cmd.go
cli/internal_data_cmds.go
cli/store_cmds.go
graph/doc.pb.go
graph/doc.proto
grapher/rule.go
plan/data.go

Depends on https://github.com/sourcegraph/srclib-go/pull/78
This uses the updated srclib-go grapher API to graph all GoPackage
units in the repo in a single call to srclib-go. This avoids the
duplicate work done to load and parse dependencies of the Go packages.
The GraphMultiUnitsRule rule will output a single GoPackage.graph.json
for the entire repo, with all defs, refs and docs in a single json file.
Observed 10x reduction in total CPU time used for building sourcegraph/sourcegraph
repo in local testing.
TODO: modify cli.Import to handle GraphMultiUnitsRule. This might be simplified
with the graph store redesign.

graph: graph all GoPackage units together, for efficiency

---

cli/store_cmds.go

This PR fixes two issues that were recently introduced with the `GraphMultiUnitsRule`:
1. Protect the shared variable `hasIndexableData` with a mutex to avoid Go race detector from complaining.
2. Use proper closure for concurrent to `importGraphData` calls within for loop. This issue would cause the graph data for certain units from never getting imported, while certain other units would be imported multiple times, within the same build.

Fix concurrency issues in import step

---

cli/toolchain_cmd.go
grapher/rule.go

- `os.Symlink` makes "file-type" symbolic links on Windows while `cd foo && make` requires "foo" to be either directory or so-called "directory symbolic link". This was the reason that  it was impossible to install go toolchain on Windows because attempt to execute `make` in file-type symbolic link failed. I also had to change execution order from (symlink, clone) to (clone, symlink) when installing Go toolchain
- thou shall not emit backslashes when generating Makefile commands, they being cut making command not runnable

Restored Windows support for Go toolchain

---

.travis.yml
cli/cli.go
cli/toolchain_cmd.go

- if toolchain contains Go code (go, python), installing it to GOPATH and symlinking GOPATH/src/TOOLCHAIN to SRCLIBPATH/TOOLCHAIN (not the opposite) to ensure that toolchain's source code is located in the GOPATH.
- installing Go toolchain in Travis to ensure that it can be installed
- (improved Windows support) when command returns an error there might be ANSI codes to control colors/effects. Using colorable wrapper to properly print messages instead of default go-flags

Fixes #281

---

plan/makefile.go
plan/makefile_test.go
vendor/vendor.json

- adding .PHONY target to generated makefile to ensure that "all" target does not clash with file names. See sourcegraph/makex#2
- updated vendored sourcegraph.com/sourcegraph/makex

Adding .PHONY target

---

cli/toolchain_cmd.go

- added 'npm install' to javascript toolchain installation steps, required since sourcegraph/srclib-javascript@06d640c18edff4d78d9abad63a07c08f02e68c22)

Fixed installation of javascript toolchain

---

gendata/simple.go
gendata/urefs.go

Don't use `fmt.Sprintf` here since it's not needed.
It's dangerous to provide dynamic input as the first parameter of a printf-like function since it may contain a sequence like `%v` which would cause a problem.

gendata: Remove unneeded fmt.Sprintf.

---

.travis.yml
cli/toolchain_cmd.go

- installing Python 3.5 in Travis build
- requiring python3.5 to be present when installing Python toolchain
- added CSS toolchain support

CSS toolchain support and Python toolchain fixes

---

README.md

The developer instructions contains instructions to install `goxc` utility, there's a minor typo in the import path and users should `go get` the path in order to fetch and install, not `go install` which requires the path to exist locally.

README: fix typos in goxc path
