docs/sources/install.md, docs/sources/plugins/emacs.md
Dear friends,
This is to update the installation guide and to resolve issue #134 (Emacs plugin).
Best regards,
Jelmer de Reus
=> Extended docs - srclib installation guide and issue #134

README.md, docs/sources/overview.md
As requested by @shurcooL and @beyang
=> Small language changes to README.md and docs/sources/overview.md

.travis.yml, Makefile, cli/gen_data_cmd.go, cli/toolchain_cmd.go
Give the `gen-data` command more parameters and the ability to generate source files.
=> Augment generate data command

cli/toolchain_cmd.go
Also requires: https://github.com/sourcegraph/srclib-go/pull/49
=> Allow `srclib toolchain install go` without GOPATH being set.

config/overrides.go
=> fix old sourcegraph URI

toolchain/docker.go
- Using suggested method (docker.NewTLSClient) to create new TLS clients
=> using new docker API to create TLS clients

cli/toolchain_cmd.go
Done with:
gofmt -w .
Fixes issue spotted in https://github.com/sourcegraph/srclib/pull/245#discussion_r51830375. /cc @beyang
=> cli: Fix gofmt issues.

cli/coverage_cmd.go, cli/validate_cmd.go
@keegancsmith do you mind giving this a sanity check?
=> Coverage command

cli/coverage_cmd.go
Coverage command for srclib data
=> Coverage cmd

cli/util.go
Made a mistake :disappointed: 
@beyang
=> cli: fix for the handling of empty json files

cli/util_test.go
=> cli: read json unit tests

docs/theme/home.html
=> fixing srclib sourcegraph link on homepage

cli/toolchain_cmd.go
- `govendor` (which is currently used by srclib-go and srclib-python) refuses to synchronize when runs not from GOPATH.
To prevent build failures, running `make` from GOPATH/src/TOOLCHAIN instead of SRCLIBDIR/TOOLCHAIN
- fixes sourcegraph/srclib#267
=> Fixed installation of Go-based toolchains

cli/store_cmds.go, dep/rule.go, grapher/rule.go
Simplify filtering by source unit name/type, and fix parallelism for GraphMultiUnitsRule import.
=> Import cmd fixes

store/indexed.go
This change removes the parallel writes that were in place previously.
In theory these parallel writes should have made import faster, but on
slower storage systems, this was causing write contention and data
=> Change srclib metadata import to create new objects in serial.

cli/coverage_cmd.go
Calculate coverage per language for greater accuracy.
=> Coverage by lang

vendor/vendor.json
- Updated sqs/fileset to include fix for sqs/fileset#2
=> Updated sqs/fileset

cli/coverage_cmd.go
- `srclib -v coverage` prints to stderr additional information such as
- orphaned references and their possible matches. For example reference's definition key may lack some attributes set for definition's key (unit, unit type, repo, ..). Candidate match is a definition that has the same path as the reference's one
- If file considered uncovered, what are the stats - density, number of defs and valid refs in it, estimated number of not-empty and not-commented-out lines of code
- Applied `gofmt`
=> Describing coverage issues with `-v` flag

cli/store_cmds.go, store/fs_store.go, store/fs_store_mock.go, store/memory.go, store/multi_repo_store.go, store/multi_repo_store_test.go, store/pb/helpers.go, store/pb/mock/srcstore.pb_mock.go, store/pb/srcstore.pb.go, store/pb/srcstore.proto, store/repo_store.go, store/repo_store_test.go
See https://app.asana.com/0/91952577398025/106673978175783
=> separate CreateVersion operation, invoked after indexers have run

toolchain/find.go
Make srclib elaborate on errors involving the scan commands to exec.
=> improve scan error messages

buildstore/store.go, cli/store_cmds.go, config/cached.go, gendata/simple.go, gendata/urefs.go, scan/scan.go, store/fs_store.go, store/indexed.go, store/indexes.go, store/repo_store.go, store/unit_store.go, vendor/vendor.json
This avoids messing up CPU and memory profiles by not adding its own stack frame.
=> replace github.com/rogpeppe/rog-go/parallel with github.com/neelance/parallel
